#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'controlador-turtlesim','console_scripts','nodo_suscriptor'
__requires__ = 'controlador-turtlesim'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('controlador-turtlesim', 'console_scripts', 'nodo_suscriptor')()
    )
