#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'control-turtlebot3','console_scripts','nodo_publicador'
__requires__ = 'control-turtlebot3'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('control-turtlebot3', 'console_scripts', 'nodo_publicador')()
    )
